name: 05-02-Event Filters and activity types
on: 
  workflow_dispatch
    types: [closed]
    branches: 
      - main
jobs:
  echo: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "running whenever a PR is closed"
 