name: 09 - Using Organization variables
on: 
  push:
  workflow_dispatch:

env:
  ORG_VAR: 'organization value'
  OVERWRITTEN_VAR: 'organization value 2'
  REPOSITORAY_VAR: 'repository value'




jobs:
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod  # Set the environment to 'prod'

    TARGET_VAR: 'prod'
    OVERWRITTEN_VAR: 'prod value'

    environment: staging  # Set the environment to 'prod'

    TARGET_VAR: 'staging'
 

    steps:
      - name: Print Prod Variables
        run: |
          # Your commands here









jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
      OVERWRITTEN: 'I have beeen overwritten'

    steps: 
      - name: Print Env Variables
        env:
          STEP_VAR: 'I am a step env var'
          step_var2: 'I am another step var'
        run: |


        
          echo " Step env var: ${{ env.STEP_VAR }}"
          echo " Step env var: ${{ env.step_var2 }}"

          echo " Step env var: ${{ env.JOB_VAR }}"
          echo " Step env var: ${{ env.OVERWRITTEN }}"

          echo " Step env var: ${{ env.WORKFLOW_VAR }}"
          echo " Step env var: ${{ env.OVERWRITTEN }}"

    
      - name: Overwrite job variable
        env:
          OVERWRITTEN: ' I have been overwritten at the step level'
        run: |
            echo "OVERWRITTEN: ${{ env.OVERWRITTEN }}"