name: 04- using actions
on:
    workflow_dispatch:
    pull_request:
jobs:
  name: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions@checkout@v4

      - name: printing folders
        run: ls
