name: 02-workflow events
on:
    workflow_dispatch:
    pull_request:
    schedule:
      - cron: '*/5 * * * *'
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
        - name: show the trigger
          run: echo "${{ github.event_name }}"


