name: My NPM Package
on: workflow_dispatch

jobs:
    node-20-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v3
              with:
                node-version: 20
            - run: npm ci
            - run: npm test
            - run: npm publish
                
   