name: 15-working with matrices
on: 
  workflow_dispatch:
    

jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    name: ${{ matrix.os }}- ${{ matrix.node }}
    strategy:
      matrix:
        node: [18, 20, 21]
        os: 
          - ubuntu-latest
          - windows-latest
    
    steps:
      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Peform some tests
        run: echo "Running tests on OS ${{ matrix.node }} and NodeJS ${{ matrix.node }}"



          
